name: ProjectRushin

options:
  minimumXcodeGenVersion: 2.30.0

configs:
  Debug: debug
  Release: release

settings:
  base:
    PRODUCT_NAME: ProjectRushin
    SWIFT_VERSION: 5.9
    IPHONEOS_DEPLOYMENT_TARGET: 16.0
  configs:
    Debug:
      SWIFT_OPTIMIZATION_LEVEL: "-Onone"
    Release:
      SWIFT_OPTIMIZATION_LEVEL: "-O"

targets:
  ProjectRushin:
    type: application
    platform: iOS

    sources:
      - path: Sources

    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.pixelatedstudios.rushin
        INFOPLIST_FILE: Info.plist

schemes:
  ProjectRushin:
    build:
      targets:
        ProjectRushin: all
    run:
      config: Debug
