name: ProjectRUSHIN
options:
  bundleIdPrefix: com.pixelatedstudios.pjrush
  deploymentTarget:
    iOS: '16.0'
configs:
  Debug: debug
  Release: release

targets:
  ProjectRUSHIN:
    type: application
    platform: iOS
    deploymentTarget: '16.0'
    sources:
      - path: Sources
    resources:
      - path: Resources
    settings:
      INFO_PLIST_FILE: Info.plist
      SWIFT_VERSION: 5.0
      CODE_SIGN_IDENTITY: ""
      CODE_SIGNING_REQUIRED: NO
      CODE_SIGNING_ALLOWED: NO

schemes:
  ProjectRUSHIN:
    build:
      targets:
        ProjectRUSHIN: all
    run:
      config: Debug