name: Build ProjectRushin (Unsigned)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_all_unsigned:
    name: Generate & Build Unsigned IPA
    runs-on: macos-26
    steps:
      - uses: actions/checkout@v4

      # Install Homebrew + XcodeGen
      - name: Install Homebrew + XcodeGen
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo 'eval "$(/opt/homebrew/bin/brew shellenv)"' >> ~/.bash_profile
          eval "$(/opt/homebrew/bin/brew shellenv)"
          brew install xcodegen

      # Generate Xcode project
      - name: Generate Project
        run: xcodegen generate --spec project.yml --project ProjectRushin.xcodeproj

      # Use latest Xcode
      - name: Use Latest Xcode
        run: sudo xcode-select -s /Applications/Xcode_26.3.app

      # Build IPA unsigned
      - name: Build Unsigned IPA
        run: |
          xcodebuild \
            -project ProjectRushin.xcodeproj \
            -scheme ProjectRushin \
            -configuration Release \
            -archivePath $PWD/build/ProjectRushin.xcarchive archive \
            CODE_SIGNING_ALLOWED=NO

          xcodebuild \
            -exportArchive \
            -archivePath $PWD/build/ProjectRushin.xcarchive \
            -exportOptionsPlist buildOptions.plist \
            -exportPath $PWD/build \
            CODE_SIGNING_ALLOWED=NO

      # Upload IPA artifact
      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: Unsigned IPA
          path: build/ProjectRushin.ipa